---
- name: Execute create_dir.yml tasks
  include_tasks: create_dir.yml

- name: Execute create_file.yml tasks
  include_tasks: create_file.yml

- name: Execute get_url.yml tasks
  include_tasks: get_url.yml
  when: url | default('false') | bool
